/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: ['./app/**/*.{js,jsx}', './components/**/*.{js,jsx}', './lib/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'primary-fixed': '#dae2fd',
        outline: '#76777d',
        'on-tertiary-container': '#009668',
        background: '#f7f9fb',
        'on-primary': '#ffffff',
        'on-surface-variant': '#45464d',
        'secondary-fixed-dim': '#adc6ff',
        'on-error-container': '#93000a',
        'error-container': '#ffdad6',
        'on-secondary-container': '#fefcff',
        'surface-variant': '#e0e3e5',
        'surface-container-high': '#e6e8ea',
        error: '#ba1a1a',
        secondary: '#0058be',
        'on-secondary-fixed': '#001a42',
        'surface-container-highest': '#e0e3e5',
        'on-background': '#191c1e',
        'on-secondary-fixed-variant': '#004395',
        surface: '#f7f9fb',
        'on-error': '#ffffff',
        'on-primary-fixed': '#131b2e',
        'on-tertiary-fixed-variant': '#005236',
        'surface-tint': '#565e74',
        'surface-container-low': '#f2f4f6',
        'tertiary-container': '#002113',
        tertiary: '#000000',
        'secondary-container': '#2170e4',
        'inverse-primary': '#bec6e0',
        'surface-dim': '#d8dadc',
        'on-primary-container': '#7c839b',
        'on-secondary': '#ffffff',
        'inverse-on-surface': '#eff1f3',
        'surface-container-lowest': '#ffffff',
        'outline-variant': '#c6c6cd',
        primary: '#000000',
        'surface-container': '#eceef0',
        'primary-fixed-dim': '#bec6e0',
        'surface-bright': '#f7f9fb',
        'inverse-surface': '#2d3133',
        'on-surface': '#191c1e',
        'on-primary-fixed-variant': '#3f465c',
        'primary-container': '#131b2e',
        'on-tertiary-fixed': '#002113',
        'tertiary-fixed': '#6ffbbe',
        'on-tertiary': '#ffffff',
        'secondary-fixed': '#d8e2ff',
        'tertiary-fixed-dim': '#4edea3',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'stack-md': '2rem',
        'margin-mobile': '1.5rem',
        gutter: '1.5rem',
        'stack-lg': '4rem',
        'stack-sm': '0.75rem',
        'container-max': '960px',
      },
      fontFamily: {
        'headline-lg': ['Hanken Grotesk', 'sans-serif'],
        'label-sm': ['Geist', 'sans-serif'],
        'button-text': ['Inter', 'sans-serif'],
        'headline-lg-mobile': ['Hanken Grotesk', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'headline-lg': ['40px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
        'label-sm': ['14px', { lineHeight: '1.4', letterSpacing: '0.02em', fontWeight: '500' }],
        'button-text': ['16px', { lineHeight: '1', fontWeight: '600' }],
        'headline-lg-mobile': ['28px', { lineHeight: '1.2', fontWeight: '700' }],
        'body-md': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
      },
    },
  },
  plugins: [require('@tailwindcss/forms'), require('@tailwindcss/container-queries')],
};
